.PHONY: clean All

All:
	@echo "----------Building project:[ CodingExercise25 - Debug ]----------"
	@cd "CodingExercise25" && "$(MAKE)" -f  "CodingExercise25.mk"
clean:
	@echo "----------Cleaning project:[ CodingExercise25 - Debug ]----------"
	@cd "CodingExercise25" && "$(MAKE)" -f  "CodingExercise25.mk" clean
