.PHONY: clean All

All:
	@echo "----------Building project:[ CodingExercise22 - Debug ]----------"
	@cd "CodingExercise22" && "$(MAKE)" -f  "CodingExercise22.mk"
clean:
	@echo "----------Cleaning project:[ CodingExercise22 - Debug ]----------"
	@cd "CodingExercise22" && "$(MAKE)" -f  "CodingExercise22.mk" clean
