.PHONY: clean All

All:
	@echo "----------Building project:[ CodingExercise24 - Debug ]----------"
	@cd "CodingExercise24" && "$(MAKE)" -f  "CodingExercise24.mk"
clean:
	@echo "----------Cleaning project:[ CodingExercise24 - Debug ]----------"
	@cd "CodingExercise24" && "$(MAKE)" -f  "CodingExercise24.mk" clean
