.PHONY: clean All

All:
	@echo "----------Building project:[ CodingExercise5 - Debug ]----------"
	@cd "CodingExercise5" && "$(MAKE)" -f  "CodingExercise5.mk"
clean:
	@echo "----------Cleaning project:[ CodingExercise5 - Debug ]----------"
	@cd "CodingExercise5" && "$(MAKE)" -f  "CodingExercise5.mk" clean
