.PHONY: clean All

All:
	@echo "----------Building project:[ EqualityOperators - Debug ]----------"
	@cd "EqualityOperatos" && "$(MAKE)" -f  "EqualityOperators.mk"
clean:
	@echo "----------Cleaning project:[ EqualityOperators - Debug ]----------"
	@cd "EqualityOperatos" && "$(MAKE)" -f  "EqualityOperators.mk" clean
