.PHONY: clean All

All:
	@echo "----------Building project:[ CodingExercise16 - Debug ]----------"
	@cd "CodingExercise16" && "$(MAKE)" -f  "CodingExercise16.mk"
clean:
	@echo "----------Cleaning project:[ CodingExercise16 - Debug ]----------"
	@cd "CodingExercise16" && "$(MAKE)" -f  "CodingExercise16.mk" clean
