.PHONY: clean All

All:
	@echo "----------Building project:[ forLoop - Debug ]----------"
	@cd "forLoop" && "$(MAKE)" -f  "forLoop.mk"
clean:
	@echo "----------Cleaning project:[ forLoop - Debug ]----------"
	@cd "forLoop" && "$(MAKE)" -f  "forLoop.mk" clean
