.PHONY: clean All

All:
	@echo "----------Building project:[ Hiekkalaatikko - Debug ]----------"
	@cd "Hiekkalaatikko" && "$(MAKE)" -f  "Hiekkalaatikko.mk"
clean:
	@echo "----------Cleaning project:[ Hiekkalaatikko - Debug ]----------"
	@cd "Hiekkalaatikko" && "$(MAKE)" -f  "Hiekkalaatikko.mk" clean
