.PHONY: clean All

All:
	@echo "----------Building project:[ CodingExercise18 - Debug ]----------"
	@cd "CodingExercise18" && "$(MAKE)" -f  "CodingExercise18.mk"
clean:
	@echo "----------Cleaning project:[ CodingExercise18 - Debug ]----------"
	@cd "CodingExercise18" && "$(MAKE)" -f  "CodingExercise18.mk" clean
